export const ERR_DUPLICATED_EMAIL = "ERR_DUPLICATED_EMAIL";

export const ERR_USER_NOT_FOUND = "ERR_USER_NOT_FOUND";

export const ERR_INVALID_PASSWORD = "ERR_INVALID_PASSWORD";

export const ERR_INVALID_TOKEN = "ERR_INVALID_TOKEN";